name: Bug
description: Found a bug in our site or source code
labels: ["bug"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the bug.
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
