name: Documentation
description: Found a typo in the documentation or some suggestions
labels: ["documentation"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: Give a brief overview of the bug like whether it's an typo, outdated content, incorrect code, etc.
    validations:
      required: true
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: false

  - type: textarea
    id: behaviour
    attributes:
      label: Expected behaviour
      description: If you are sure of how the problem should be intended to solve or actual expected outcome, proceed further. 🤫This can lead your way to becoming an open source contribution as well.
    validations:
      required: false

