name: Feature request
description: Found a typo in the documentation or some suggestions
labels: ["enchancement"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: How we can improve the Naas ecosystem better? Have a cool idea/feature let us know.
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
    validations:
      required: false
