name: Others
description: Use this if your issue doesn't fall into any other category
labels: ["question"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Provide a clear description of the problem faced
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any thing else that you need to let us know...
    validations:
      required: false
